### ISSUE TITLE
Added Footer section

### ISSUE THREAD

**Issue by Shrutibansal22** [SamsShow/EnerXchange-Frontend#1]
I would love to add footer section in this amazing website .
kindly assign me this issue.

**Comment by SamsShow** [comment]
sure

**Comment by Shrutibansal22** [comment]
could you plz assign me under label of gssoc .

**Comment by SamsShow** [comment]
> could you plz assign me under label of gssoc .

this project is not a part of gssoc

**Comment by Shrutibansal22** [comment]
sir plz added label of hacktoberfesr2024 also

**Comment by SamsShow** [comment]
> sir plz added label of hacktoberfesr2024 also

added
