### ISSUE TITLE
Remove the unwanted spacing

### ISSUE THREAD

**Issue by Bhavishya2601** [SamsShow/EnerXchange-Frontend#12]
There is some unwanted spacing near header and footer
![Screenshot 2024-10-13 133900](https://github.com/user-attachments/assets/889979e8-141b-4be6-a7b9-ce127718b583)
![Screenshot 2024-10-13 133909](https://github.com/user-attachments/assets/ce5ad80c-510e-4384-b277-8ffb19894aa3)

i would like to work on this issue under hactoberfest

**Comment by SamsShow** [comment]
i think someone is working on fixing the footer so let that issue get resolved otherwise, it might conflict

**Comment by SamsShow** [comment]
please don't create separate issues for these small changes you could have fixed it in your previous PR which was related to fotter only
PR #6

**Comment by Bhavishya2601** [comment]
I didn't really notice it when I was working on the previous issue
