### ISSUE TITLE
Adding functionality to buttons

### ISSUE THREAD

**Issue by Bhavishya2601** [SamsShow/EnerXchange-Frontend#18]
The buttons on the homepage doesn't work like the sell energy, buy energy and get started.

I would like to work on this issue under hactoberfest

**Comment by SamsShow** [comment]
please don't create separate Issues, you can compile all these in a single issue

**Comment by Bhavishya2601** [comment]
ok, i will add some more changes
like the spaces i mentioned before
and there is also this section where the font-size, I think is too small as compared to the picture
so i think of either increasing the font size or adding more points
![Screenshot 2024-10-15 101153](https://github.com/user-attachments/assets/2362cef6-f455-4f52-b105-7c905b8e42c4)
